### ISSUE TITLE
Invalid request-target according to the RFC

### ISSUE THREAD

**Issue by dieterde** [DavidLievrouw/HttpMessageSigning#10]
According to the RFC (https://tools.ietf.org/html/draft-cavage-http-signatures-12#section-2.3), the request-target should contain the request parameters, which are excluded by the library in the Extensions.HttpRequestMessage class (https://github.com/DavidLievrouw/HttpMessageSigning/blob/90bf3c77818855c092063af6ac363fa3e98fa9d7/src/HttpMessageSigning/Extensions.HttpRequestMessage.cs).

I believe this should be the fix:
`var requestForSigning = new HttpRequestForSigning {
                Method = httpRequestMessage.Method,
                RequestUri = httpRequestMessage.RequestUri.IsAbsoluteUri
                    ? httpRequestMessage.RequestUri.PathAndQuery.UrlDecode()
                    : httpRequestMessage.RequestUri.OriginalString.UrlDecode()
            };`

**Comment by DavidLievrouw** [comment]
Yes, this appears to be correct, as stated here:
https://tools.ietf.org/html/rfc7540#section-8.1.2.3
https://tools.ietf.org/html/rfc3986#section-3.3

This is a breaking change, since query strings are ignored up until the current version. This will be scheduled for the next major v5.

Scope of the change:
- Suggested change from @dieterde + covering unit tests
- Acceptance tests that include the query string parameters in the (request-target) pseudo header value

**Comment by DavidLievrouw** [comment]
Thank you for your suggestion.

The fix will be included in v5.0.0.

**Comment by dieterde** [comment]
There should be an additional (small) fix. Why is the requestUri URL decoded? It's not necessary, if the URL is encoded it should be taken this way otherwise the verification process fails.

So this is the change:
`var requestForSigning = new HttpRequestForSigning {
                Method = httpRequestMessage.Method,
                RequestUri = httpRequestMessage.RequestUri.IsAbsoluteUri
                    ? httpRequestMessage.RequestUri.PathAndQuery
                    : httpRequestMessage.RequestUri.OriginalString.Split('#')[0]
            };`
