### ISSUE TITLE
Nonce not required to be included in list of required headers

### ISSUE THREAD

**Issue by ghost** [DavidLievrouw/HttpMessageSigning#35]
https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-04#section-2.1 seems to indicate that headers included in the signature should be listed as comma separate list.

We are able to create signatures that do not list nonce as a required header in the headers= property. 

Is this a bug in the library? Since it requires nonce to be a part of the signature, shouldn't it also be a part of the headers= property? Or am I misunderstanding something?

**Comment by DavidLievrouw** [comment]
~~Should not be possible, indeed. When setting `EnableNonce` to `true`, the `nonce` header name should be included in the list of headers.~~

Okay, I might have misunderstood the issue here. 
Nonce is a parameter field, not a header. When you set `EnableNonce` to `true`, a uniquely valued **parameter field** is added to the authorization header parameter, not a HTTP header. E.g.
`
keyId="CanIncludeNonceInSignature",algorithm="hs2019",created=1619363882,expires=1619364182,headers="dalion-app-id",nonce="-4uGO1JKFE2flXVrKDA9Jw",signature="5ippRjo3GG3p/rYCnUsza0Wd+5Vj0F/mIGqBwN3a2RIDbNr7uYRA1SYoS0K/0tWfdGpOzCU+Ae2OadDP0DtFxw=="
`

You can still add a separate "Nonce" header, and include it in the signature, by specifying it in the `SigningSettings.Headers` property. But that's not what the `EnableNonce` setting is about. See https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-04#section-2.4.2.

> Please note that we currently conform with [v00](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-00). Confirming with [v04](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-04) is a breaking change, and is currently in the works... #27 

Let me know if this answers your question. If not, it would help to get a code sample that replays the problem. Thanks.

**Comment by ghost** [comment]
Thank you for clarifying the difference between header and parameter with respect to signing.

I believe there is no issue.
